# Generated by Django 2.1.4 on 2018-12-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('u_password', models.CharField(max_length=20)),
                ('u_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateTimeField()),
                ('a_time', models.IntegerField()),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.User')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
