# Generated by Django 2.1.4 on 2018-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='s_char',
            field=models.CharField(default='', max_length=10),
        ),
    ]
