# Generated by Django 2.1.4 on 2018-12-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_exam_studentexam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstudent',
            unique_together={('u_name', 's_id')},
        ),
    ]
