# Generated by Django 2.1.4 on 2018-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20181206_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jwc_passwd',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
