# Generated by Django 2.1.4 on 2018-12-07 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_jwc_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='e_pos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='e_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 9, 30)),
        ),
    ]
